name: news_boys
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  dio: ^5.4.0
  fancy_shimmer_image: ^2.0.3
  flutter_native_splash: ^1.1.8
  flutter:
    sdk: flutter
  http: ^0.13.5
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/